const SearchPage = () => {
  return (
    <div>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
      <ul>s</ul>
    </div>
  )
}

export default SearchPage
